STAR_HIEROGLYPHS = [
    {
        "name": "Peacock",
        "distance": 179,
        "longitude": 318.61,
        "latitude": -36.92,
        "size": 25,
        "hieroglyph": "𓋔",
        "egyptian_name": "Red Crown",
        "gardiner": "S3",
        "description": "Lower Egypt crown",
        "color": "#00FF00",  # 🟩 Tier 4
    },
    {
        "name": "Ras Algethi",
        "distance": 360,
        "longitude": 60.14,
        "latitude": 36.96,
        "size": 25,
        "hieroglyph": "𓆣",
        "egyptian_name": "Scarab/Khepri",
        "gardiner": "L1",
        "description": "Khepri, rebirth deity",
        "color": "#FFA500",  # 🟧 Tier 2
    },
    {
        "name": "Atria",
        "distance": 416,
        "longitude": 322.91,
        "latitude": -14.61,
        "size": 25,
        "hieroglyph": "𓇼",
        "egyptian_name": "Star",
        "gardiner": "N14",
        "description": "Celestial star symbol",
        "color": "#FFFF00",  # 🟨 Tier 3
    },
    {
        "name": "Alphecca",
        "distance": 75,
        "longitude": 67.14,
        "latitude": 26.70,
        "size": 25,
        "hieroglyph": "𓉖",
        "egyptian_name": "Throne",
        "gardiner": "Q1/Q3",
        "description": "Royal seat",
        "color": "#00FF00",  # 🟩 Tier 4
    },
    {
        "name": "Denebola",
        "distance": 36,
        "longitude": 182.53,
        "latitude": 14.57,
        "size": 25,
        "hieroglyph": "𓄿",
        "egyptian_name": "Sekhmet/Lioness",
        "gardiner": "E22/E23",
        "description": "Warrior goddess",
        "color": "#FFA500",  # 🟧 Tier 2
    },
    {
        "name": "Almach",
        "distance": 350,
        "longitude": 111.67,
        "latitude": -8.87,
        "size": 25,
        "hieroglyph": "𓊵",
        "egyptian_name": "Ptah",
        "gardiner": "C20",
        "description": "Cosmic architect of order",
        "color": "#FFA500",  # 🟧 Tier 2
    },
    {
        "name": "Adhara",
        "distance": 405,
        "longitude": 255.24,
        "latitude": -8.92,
        "size": 25,
        "hieroglyph": "𓍯",
        "egyptian_name": "Cartouche",
        "gardiner": "V10",
        "description": "Royal name enclosure",
        "color": "#00FF00",  # 🟩 Tier 4
    },
    {
        "name": "Rastaban",
        "distance": 380,
        "longitude": 91.24,
        "latitude": 36.45,
        "size": 25,
        "hieroglyph": "𓊶",
        "egyptian_name": "Obelisk",
        "gardiner": "O25",
        "description": "Monument of power",
        "color": "#00FF00",  # 🟩 Tier 4
    },
    {
        "name": "Acrux",
        "distance": 321,
        "longitude": 300.13,
        "latitude": -0.36,
        "size": 25,
        "hieroglyph": "𓌉",
        "egyptian_name": "Was Scepter",
        "gardiner": "S39/S40",
        "description": "Symbol of power",
        "color": "#00FF00",  # 🟩 Tier 4
    },
    {
        "name": "Alkes",
        "distance": 87,
        "longitude": 243.17,
        "latitude": -6.53,
        "size": 25,
        "hieroglyph": "𓊵",
        "egyptian_name": "Offering Table",
        "gardiner": "R3/R4/R7",
        "description": "Ritual offering platform",
        "color": "#00FF00",  # 🟩 Tier 4
    },
    {
        "name": "Miaplacidus",
        "distance": 113,
        "longitude": 258.97,
        "latitude": -19.25,
        "size": 25,
        "hieroglyph": "𓊨",
        "egyptian_name": "Solar Barque",
        "gardiner": "P1/P4",
        "description": "Ra’s celestial boat",
        "color": "#FFFF00",  # 🟨 Tier 3
    },
    {
        "name": "Elnath",
        "distance": 131,
        "longitude": 174.32,
        "latitude": 5.22,
        "size": 25,
        "hieroglyph": "𓄡",
        "egyptian_name": "Seth/Set",
        "gardiner": "E20/C7",
        "description": "God of chaos and storms",
        "color": "#FFA500",  # 🟧 Tier 2
    },
    {
        "name": "Unukalhai",
        "distance": 74,
        "longitude": 36.13,
        "latitude": 12.25,
        "size": 25,
        "hieroglyph": "𓌅",
        "egyptian_name": "Flail",
        "gardiner": "S45",
        "description": "Royal harvest symbol",
        "color": "#00FF00",  # 🟩 Tier 4
    },
    {
        "name": "Alnilam",
        "distance": 1340,
        "longitude": 196.96,
        "latitude": -1.12,
        "size": 25,
        "hieroglyph": "𓊍",
        "egyptian_name": "Pyramid",
        "gardiner": "O24",
        "description": "Funerary monument",
        "color": "#00FF00",  # 🟩 Tier 4
    },
    {
        "name": "Capella",
        "distance": 42.9,
        "longitude": 162.58,
        "latitude": 4.57,
        "size": 25,
        "hieroglyph": "𓇳",
        "egyptian_name": "Aten (Sun Disk)",
        "gardiner": "N5",
        "description": "Golden solar disk of Aten",
        "color": "#FF0000",
    },
    {
        "name": "Hamal",
        "distance": 66,
        "longitude": 145.13,
        "latitude": 29.96,
        "size": 25,
        "hieroglyph": "𓂀",
        "egyptian_name": "Eye of Ra/Wadjet",
        "gardiner": "D10",
        "description": "Fiery protective eye",
        "color": "#FF0000",
    },
    {
        "name": "Alphard",
        "distance": 177,
        "longitude": 218.67,
        "latitude": -8.86,
        "size": 25,
        "hieroglyph": "𓅣",
        "egyptian_name": "Bennu (Phoenix)",
        "gardiner": "G31",
        "description": "Solitary phoenix of rebirth",
        "color": "#FFA500",
    },
    {
        "name": "Bellatrix",
        "distance": 250,
        "longitude": 195.52,
        "latitude": 6.22,
        "size": 25,
        "hieroglyph": "𓋳",
        "egyptian_name": "Sa Sign",
        "gardiner": "V31/V37",
        "description": "Protective warrior symbol",
        "color": "#00FF00",
    },
    {
        "name": "Dubhe",
        "distance": 123,
        "longitude": 121.94,
        "latitude": 61.45,
        "size": 25,
        "hieroglyph": "𓋴",
        "egyptian_name": "Sema Tawy",
        "gardiner": "F36",
        "description": "Unification of Egypt",
        "color": "#00FF00",
    },
    {
        "name": "Kochab",
        "distance": 126,
        "longitude": 112.65,
        "latitude": 40.50,
        "size": 35,
        "hieroglyph": "𓍢",
        "egyptian_name": "Tyet",
        "gardiner": "V36/V39",
        "description": "Isis Knot",
        "color": "#9370DB",
    },
    {
        "name": "Rasalhague",
        "distance": 47,
        "longitude": 35.90,
        "latitude": 22.57,
        "size": 35,
        "hieroglyph": "𓋚",
        "egyptian_name": "White Crown",
        "gardiner": "S1",
        "description": "Royal Authority",
        "color": "#F0E68C",
    },
    # Special cases
    {
        "name": "Dark Energy",
        "distance": 26000,
        "longitude": 0,
        "latitude": 0,
        "size": 30,
        "hieroglyph": "𓌻",
        "egyptian_name": "Magic/Heka",
        "gardiner": "U6/A2",
        "description": "Heart of the Underworld",
        "color": "#000000",
    },
    {
        "name": "Dark Matter",
        "distance": 25900,
        "longitude": 0,
        "latitude": 0,
        "size": 30,
        "hieroglyph": "𓊽",
        "egyptian_name": "Djed Pillar",
        "gardiner": "R11",
        "description": "Stability Unseen",
        "color": "#2F4F4F",
    },
    {
        "name": "Milky Way Rotation",
        "distance": 29000,
        "longitude": 180,
        "latitude": 0,
        "size": 30,
        "hieroglyph": "𓇯",
        "egyptian_name": "Nut/Sky",
        "gardiner": "C23/C9/N1",
        "description": "Celestial Sky Goddess",
        "color": "#4B0082",
    },
    # Count=4 consensus stars
    {
        "name": "Sirius",
        "distance": 9,
        "longitude": 227.23,
        "latitude": -8.89,
        "size": 35,
        "hieroglyph": "𓋹",
        "egyptian_name": "Sopdet/Ankh",
        "gardiner": "S34",
        "description": "Life Force",
        "color": "#ADD8E6",
    },
    {
        "name": "Vega",
        "distance": 25,
        "longitude": 67.44,
        "latitude": 19.24,
        "size": 25,
        "hieroglyph": "𓂀",
        "egyptian_name": "Eye of Horus",
        "gardiner": "D10",
        "description": "Eye of Horus",
        "color": "#E0FFFF",
    },
    {
        "name": "Sol",
        "distance": 0,
        "longitude": 180.00,
        "latitude": 0.00,
        "size": 40,
        "hieroglyph": "𓇳",
        "egyptian_name": "Sun/Ra",
        "gardiner": "N5",
        "description": "The Solar Disc",
        "color": "#FFFF00",
    },
    {
        "name": "Spica",
        "distance": 262,
        "longitude": 316.11,
        "latitude": 50.84,
        "size": 25,
        "hieroglyph": "𓈈",
        "egyptian_name": "Horizon/Akhet",
        "gardiner": "N27",
        "description": "Horizon of Ra",
        "color": "#7B68EE",
    },
    {
        "name": "Polaris",
        "distance": 433,
        "longitude": 123.28,
        "latitude": 26.46,
        "size": 25,
        "hieroglyph": "𓂃",
        "egyptian_name": "Anubis",
        "gardiner": "E17/E16",
        "description": "Guardian of the North",
        "color": "#4169E1",
    },
    {
        "name": "Regulus",
        "distance": 79,
        "longitude": 226.43,
        "latitude": 48.93,
        "size": 25,
        "hieroglyph": "𓃠",
        "egyptian_name": "Bastet/Cat",
        "gardiner": "B1/E13",
        "description": "Lion’s Heart",
        "color": "#FFD700",
    },
    {
        "name": "Thuban",
        "distance": 303,
        "longitude": 97.00,
        "latitude": 47.60,
        "size": 25,
        "hieroglyph": "𓆓",
        "egyptian_name": "Cobra/Uraeus",
        "gardiner": "I10/I12",
        "description": "Serpent of Kingship",
        "color": "#228B22",
    },
    {
        "name": "Fomalhaut",
        "distance": 25,
        "longitude": 20.00,
        "latitude": -64.90,
        "size": 25,
        "hieroglyph": "𓆄",
        "egyptian_name": "Crocodile/Sobek",
        "gardiner": "I3/I4",
        "description": "Nile Crocodile",
        "color": "#00CED1",
    },
    {
        "name": "Altair",
        "distance": 17,
        "longitude": 47.74,
        "latitude": -8.87,
        "size": 25,
        "hieroglyph": "𓅃",
        "egyptian_name": "Falcon/Horus",
        "gardiner": "G5",
        "description": "Winged Deity",
        "color": "#B0E0E6",
    },
    {
        "name": "Antares",
        "distance": 550,
        "longitude": 351.00,
        "latitude": 15.00,
        "size": 30,
        "hieroglyph": "𓄤",
        "egyptian_name": "Heart",
        "gardiner": "F34",
        "description": "Scorpion’s Heart",
        "color": "#FF4500",
    },
    {
        "name": "Deneb",
        "distance": 2600,
        "longitude": 84.00,
        "latitude": 1.90,
        "size": 30,
        "hieroglyph": "𓅜",
        "egyptian_name": "Ibis/Thoth",
        "gardiner": "G26/C3",
        "description": "Scribe of the Gods",
        "color": "#F0FFFF",
    },
    {
        "name": "Canopus",
        "distance": 310,
        "longitude": 261.00,
        "latitude": -25.30,
        "size": 30,
        "hieroglyph": "𓇼",
        "egyptian_name": "Isis",
        "gardiner": "C2/C10/C20",
        "description": "Throne Goddess",
        "color": "#FFF5EE",
    },
    {
        "name": "Procyon",
        "distance": 11,
        "longitude": 213.00,
        "latitude": 13.00,
        "size": 25,
        "hieroglyph": "𓃢",
        "egyptian_name": "Jackal",
        "gardiner": "E16/E17",
        "description": "Faithful Guardian",
        "color": "#FFE4B5",
    },
    {
        "name": "Aldebaran",
        "distance": 65,
        "longitude": 181.00,
        "latitude": -20.00,
        "size": 25,
        "hieroglyph": "𓃬",
        "egyptian_name": "Bes/Lion",
        "gardiner": "E23/E1",
        "description": "Eye of the Bull",
        "color": "#FF6347",
    },
    {
        "name": "Sigma Draconis",
        "distance": 19,
        "longitude": 280.46,
        "latitude": 32.75,
        "size": 35,
        "hieroglyph": "𓆰",
        "egyptian_name": "Lotus",
        "gardiner": "M1/M9",
        "description": "Blossom of Creation",
        "color": "#FFDAB9",
    },
    {
        "name": "Delta Cephei",
        "distance": 887,
        "longitude": 84.29,
        "latitude": 22.52,
        "size": 25,
        "hieroglyph": "𓇼",
        "egyptian_name": "Moon",
        "gardiner": "N11/N30",
        "description": "Cycles of Khonsu",
        "color": "#F5F5F5",
    },
    {
        "name": "Betelgeuse",
        "distance": 550,
        "longitude": 199.78,
        "latitude": -8.93,
        "size": 30,
        "hieroglyph": "𓇳",
        "egyptian_name": "Osiris",
        "gardiner": "A40/C1/C12",
        "description": "Dying and Rising God",
        "color": "#FF0000",
    },
    {
        "name": "Alpha Centauri",
        "distance": 4,
        "longitude": 315.78,
        "latitude": -0.68,
        "size": 35,
        "hieroglyph": "𓎟",
        "egyptian_name": "Shen Ring",
        "gardiner": "V9",
        "description": "Eternal Return",
        "color": "#FFFFFF",
    },
    {
        "name": "Epsilon Indi",
        "distance": 12,
        "longitude": 336.21,
        "latitude": -48.04,
        "size": 35,
        "hieroglyph": "𓅡",
        "egyptian_name": "Vulture",
        "gardiner": "G1/G14",
        "description": "Underworld Bird",
        "color": "#8B0000",
    },
    {
        "name": "Achernar",
        "distance": 139,
        "longitude": 290.68,
        "latitude": -58.79,
        "size": 30,
        "hieroglyph": "𓈗",
        "egyptian_name": "Water/Waves",
        "gardiner": "N35",
        "description": "Waters of Nun",
        "color": "#1E90FF",
    },
    {
        "name": "Mira",
        "distance": 300,
        "longitude": 170.54,
        "latitude": -58.78,
        "size": 25,
        "hieroglyph": "𓅛",
        "egyptian_name": "Ba Bird",
        "gardiner": "G29/G53",
        "description": "The Soul",
        "color": "#FFEFD5",
    },
    {
        "name": "Delta Pavonis",
        "distance": 20,
        "longitude": 311.76,
        "latitude": -36.31,
        "size": 35,
        "hieroglyph": "𓌂",
        "egyptian_name": "Crook",
        "gardiner": "S38/S42",
        "description": "Shepherd’s Staff",
        "color": "#AFEEEE",
    },
    {
        "name": "Albireo",
        "distance": 430,
        "longitude": 62.08,
        "latitude": 5.11,
        "size": 25,
        "hieroglyph": "𓆣",
        "egyptian_name": "Double Crown",
        "gardiner": "S4/S5",
        "description": "Union of Two Lands",
        "color": "#DA70D6",
    },
    {
        "name": "Algol",
        "distance": 93,
        "longitude": 150.00,
        "latitude": -22.00,
        "size": 25,
        "hieroglyph": "𓆄",
        "egyptian_name": "Feather/Maat",
        "gardiner": "H6",
        "description": "Star of Fate",
        "color": "#DC143C",
    },
    {
        "name": "Alcyone",
        "distance": 444,
        "longitude": 167.02,
        "latitude": -23.46,
        "size": 30,
        "hieroglyph": "𓃞",
        "egyptian_name": "Hathor/Cow",
        "gardiner": "E1/E4/C9",
        "description": "Seven Sisters",
        "color": "#87CEEB",
    },
    {
        "name": "Hadar",
        "distance": 390,
        "longitude": 315.09,
        "latitude": 1.35,
        "size": 30,
        "hieroglyph": "𓃩",
        "egyptian_name": "Taweret/Hippo",
        "gardiner": "E25/E24",
        "description": "River Beast",
        "color": "#A9A9A9",
    },
    {
        "name": "Van Maanen",
        "distance": 14,
        "longitude": 70.00,
        "latitude": -34.00,
        "size": 20,
        "hieroglyph": "𓂓",
        "egyptian_name": "Ka",
        "gardiner": "D28",
        "description": "Vital Essence",
        "color": "#FFFFFF",
    },
]
