STAR_HIEROGLYPHS = [
    # low confidence of match fidelity
    {
        "name": "Castor",
        "distance": 51.53,
        "longitude": 113.5,
        "latitude": 31.88,
        "size": 35,
        "hieroglyph": "𓇅",
        "egyptian_name": "Papyrus",
        "gardiner": "M16/M17",
        "description": "Sacred Writing",
        "color": "#90EE90",
    },
    {
        "name": "Hamal",
        "distance": 65.89,
        "longitude": 31.78,
        "latitude": 23.46,
        "size": 40,
        "hieroglyph": "𓄿",
        "egyptian_name": "Ram",
        "gardiner": "E10",
        "description": "Divine Power",
        "color": "#F4A460",
    },
    {
        "name": "Elnath",
        "distance": 134,
        "longitude": 81.57,
        "latitude": 28.61,
        "size": 35,
        "hieroglyph": "𓋔",
        "egyptian_name": "Red Crown",
        "gardiner": "S3",
        "description": "Lower Egypt",
        "color": "#DC143C",
    },
    {
        "name": "70 Aquilae",
        "distance": 940,
        "longitude": 90.3,
        "latitude": 15.5,
        "size": 35,
        "hieroglyph": "𓂀",
        "egyptian_name": "Sekhmet",
        "gardiner": "A1",
        "description": "Fiery Guardian",
        "color": "#FF6347",
    },
    {
        "name": "Kaus Media",
        "distance": 170,
        "longitude": 274.19,
        "latitude": -26.46,
        "size": 35,
        "hieroglyph": "𓄡",
        "egyptian_name": "Seth",
        "gardiner": "E20/C7",
        "description": "Storm Bringer",
        "color": "#8B0000",
    },
    {
        "name": "Rastaban",
        "distance": 380,
        "longitude": 268.31,
        "latitude": 52.93,
        "size": 35,
        "hieroglyph": "𓊨",
        "egyptian_name": "Throne",
        "gardiner": "Q1/Q3",
        "description": "Royal Seat",
        "color": "#4169E1",
    },
    {
        "name": "Kochab",
        "distance": 130,
        "longitude": 222.59,
        "latitude": 74.18,
        "size": 35,
        "hieroglyph": "𓍢",
        "egyptian_name": "Tyet",
        "gardiner": "V36/V39",
        "description": "Isis Knot",
        "color": "#9370DB",
    },
    {
        "name": "Epsilon Indi",
        "distance": 11.82,
        "longitude": 330.0,
        "latitude": -48.0,
        "size": 35,
        "hieroglyph": "𓍱",
        "egyptian_name": "Offering Table",
        "gardiner": "R3/R4/R7",
        "description": "Abundance Offering",
        "color": "#ADD8E6",
    },
    {
        "name": "Rasalhague",
        "distance": 48,
        "longitude": 96.7,
        "latitude": 12.3,
        "size": 35,
        "hieroglyph": "𓋚",
        "egyptian_name": "White Crown",
        "gardiner": "S1",
        "description": "Royal Authority",
        "color": "#F0E68C",
    },
    {
        "name": "Schedar",
        "distance": 228,
        "longitude": 10.1,
        "latitude": -2.5,
        "size": 35,
        "hieroglyph": "𓍯",
        "egyptian_name": "Cartouche",
        "gardiner": "V10",
        "description": "Royal Enclosure",
        "color": "#B0E0E6",
    },
    {
        "name": "Adhara",
        "distance": 405,
        "longitude": 76.2,
        "latitude": -11.3,
        "size": 35,
        "hieroglyph": "𓊶",
        "egyptian_name": "Pyramid",
        "gardiner": "O24",
        "description": "Eternal Monument",
        "color": "#FFB6C1",
    },
    {
        "name": "Shaula",
        "distance": 570,
        "longitude": 247.6,
        "latitude": -37.1,
        "size": 35,
        "hieroglyph": "𓊵",
        "egyptian_name": "Obelisk",
        "gardiner": "O25",
        "description": "Skyward Pillar",
        "color": "#ADD8E6",
    },
    {
        "name": "Scheat",
        "distance": 196,
        "longitude": 351.2,
        "latitude": 29.0,
        "size": 25,
        "hieroglyph": "𓐍",
        "egyptian_name": "Shadow",
        "gardiner": "D63",
        "description": "Variable Dimming",
        "color": "#D3D3D3",
    },
    {
        "name": "Nunki",
        "distance": 228,
        "longitude": 279.2,
        "latitude": -26.3,
        "size": 35,
        "hieroglyph": "𓊛",
        "egyptian_name": "Solar Barque",
        "gardiner": "P1/P4",
        "description": "Ra's Journey",
        "color": "#ADD8E6",
    },
    {
        "name": "Alpheratz",
        "distance": 97,
        "longitude": 112.3,
        "latitude": -15.2,
        "size": 35,
        "hieroglyph": "𓅍",
        "egyptian_name": "Owl",
        "gardiner": "G17",
        "description": "Wisdom Guide",
        "color": "#E0FFFF",
    },
    # Special cases - check gardiner for magic/heka
    {
        "name": "Dark Energy",
        "distance": 26000,
        "longitude": 0,
        "latitude": 0,
        "size": 30,
        "hieroglyph": "𓌻",
        "egyptian_name": "Magic/Heka",
        "gardiner": "U6/A2",
        "description": "Heart of the Underworld",
        "color": "#000000",
    },
    {
        "name": "Dark Matter",
        "distance": 25900,
        "longitude": 0,
        "latitude": 0,
        "size": 30,
        "hieroglyph": "𓊽",
        "egyptian_name": "Djed Pillar",
        "gardiner": "R11",
        "description": "Stability Unseen",
        "color": "#2F4F4F",
    },
    {
        "name": "Milky Way Rotation",
        "distance": 29000,
        "longitude": 180,
        "latitude": 0,
        "size": 30,
        "hieroglyph": "𓇯",
        "egyptian_name": "Nut/Sky",
        "gardiner": "N1/C9/C23",
        "description": "Celestial Sky Goddess",
        "color": "#4B0082",
    },
    # Count=4 consensus stars
    {
        "name": "Sirius",
        "distance": 8.6,
        "longitude": 227,
        "latitude": -8.9,
        "size": 35,
        "hieroglyph": "𓋹",
        "egyptian_name": "Ankh",
        "gardiner": "S34",
        "description": "Life Force",
        "color": "#ADD8E6",
    },
    {
        "name": "Vega",
        "distance": 25,
        "longitude": 67,
        "latitude": 19.2,
        "size": 25,
        "hieroglyph": "𓂀",
        "egyptian_name": "Eye of Horus",
        "gardiner": "D10",
        "description": "Eye of Horus",
        "color": "#E0FFFF",
    },
    {
        "name": "Sol",
        "distance": 0,
        "longitude": 180,
        "latitude": 0,
        "size": 40,
        "hieroglyph": "𓇳",
        "egyptian_name": "Sun/Ra",
        "gardiner": "N5",
        "description": "The Solar Disc",
        "color": "#FFFF00",
    },
    {
        "name": "Spica",
        "distance": 250,
        "longitude": 316,
        "latitude": 50.8,
        "size": 25,
        "hieroglyph": "𓈈",
        "egyptian_name": "Horizon/Akhet",
        "gardiner": "N27",
        "description": "Horizon of Ra",
        "color": "#7B68EE",
    },
    {
        "name": "Polaris",
        "distance": 433,
        "longitude": 123,
        "latitude": 27.1,
        "size": 25,
        "hieroglyph": "𓃻",
        "egyptian_name": "Anubis",
        "gardiner": "E16/E17",
        "description": "Guardian of the North",
        "color": "#4169E1",
    },
    {
        "name": "Regulus",
        "distance": 79,
        "longitude": 226,
        "latitude": 48.9,
        "size": 25,
        "hieroglyph": "𓃠",
        "egyptian_name": "Bastet/Cat",
        "gardiner": "B1/E13",
        "description": "Lion’s Heart",
        "color": "#FFD700",
    },
    {
        "name": "Thuban",
        "distance": 303,
        "longitude": 97,
        "latitude": 47.6,
        "size": 25,
        "hieroglyph": "𓆓",
        "egyptian_name": "Cobra/Uraeus",
        "gardiner": "I10/I12",
        "description": "Serpent of Kingship",
        "color": "#228B22",
    },
    {
        "name": "Fomalhaut",
        "distance": 25,
        "longitude": 20,
        "latitude": -64.9,
        "size": 25,
        "hieroglyph": "𓆄",
        "egyptian_name": "Crocodile/Sobek",
        "gardiner": "I3/I4",
        "description": "Nile Crocodile",
        "color": "#00CED1",
    },
    {
        "name": "Altair",
        "distance": 17,
        "longitude": 48,
        "latitude": -8.9,
        "size": 25,
        "hieroglyph": "𓅃",
        "egyptian_name": "Falcon/Horus",
        "gardiner": "G5",
        "description": "Winged Deity",
        "color": "#B0E0E6",
    },
    {
        "name": "Antares",
        "distance": 550,
        "longitude": 351,
        "latitude": 15,
        "size": 30,
        "hieroglyph": "𓄤",
        "egyptian_name": "Heart",
        "gardiner": "F34",
        "description": "Scorpion’s Heart",
        "color": "#FF4500",
    },
    {
        "name": "Deneb",
        "distance": 2600,
        "longitude": 84,
        "latitude": 1.9,
        "size": 30,
        "hieroglyph": "𓅜",
        "egyptian_name": "Ibis/Thoth",
        "gardiner": "G26/C3",
        "description": "Scribe of the Gods",
        "color": "#F0FFFF",
    },
    {
        "name": "Canopus",
        "distance": 310,
        "longitude": 261,
        "latitude": -25.3,
        "size": 30,
        "hieroglyph": "𓇼",
        "egyptian_name": "Isis",
        "gardiner": "C2/C10/C20",
        "description": "Throne Goddess",
        "color": "#FFF5EE",
    },
    {
        "name": "Procyon",
        "distance": 11.5,
        "longitude": 213,
        "latitude": 13,
        "size": 25,
        "hieroglyph": "𓃢",
        "egyptian_name": "Jackal",
        "gardiner": "E16/E17",
        "description": "Faithful Guardian",
        "color": "#FFE4B5",
    },
    {
        "name": "Aldebaran",
        "distance": 65,
        "longitude": 181,
        "latitude": -20,
        "size": 25,
        "hieroglyph": "𓃬",
        "egyptian_name": "Lion",
        "gardiner": "E1/E23",
        "description": "Eye of the Bull",
        "color": "#FF6347",
    },
    {
        "name": "Capella",
        "distance": 42,
        "longitude": 163,
        "latitude": 4.6,
        "size": 25,
        "hieroglyph": "𓆰",
        "egyptian_name": "Lotus",
        "gardiner": "M1/M9",
        "description": "Blossom of Creation",
        "color": "#FFDAB9",
    },
    {
        "name": "Sheliak",
        "distance": 960,
        "longitude": 71,
        "latitude": -4.6,
        "size": 25,
        "hieroglyph": "𓇼",
        "egyptian_name": "Moon",
        "gardiner": "N11/N30",
        "description": "Cycles of Khonsu",
        "color": "#F5F5F5",
    },
    {
        "name": "Betelgeuse",
        "distance": 550,
        "longitude": 200,
        "latitude": -8.2,
        "size": 30,
        "hieroglyph": "𓇳",
        "egyptian_name": "Osiris",
        "gardiner": "A40/C1/C12",
        "description": "Dying and Rising God",
        "color": "#FF0000",
    },
    {
        "name": "Rigel",
        "distance": 860,
        "longitude": 210,
        "latitude": -25,
        "size": 30,
        "hieroglyph": "𓆣",
        "egyptian_name": "Scarab/Khepri",
        "gardiner": "L1",
        "description": "Becoming, Renewal",
        "color": "#87CEFA",
    },
    {
        "name": "Alpha Centauri",
        "distance": 4.37,
        "longitude": 315,
        "latitude": -0.7,
        "size": 35,
        "hieroglyph": "𓎟",
        "egyptian_name": "Shen Ring",
        "gardiner": "V9",
        "description": "Eternal Return",
        "color": "#FFFFFF",
    },
    {
        "name": "Acrux",
        "distance": 320,
        "longitude": 320,
        "latitude": -0.5,
        "size": 25,
        "hieroglyph": "𓅃",
        "egyptian_name": "Vulture",
        "gardiner": "G1/G14",
        "description": "Underworld Bird",
        "color": "#8B0000",
    },
    {
        "name": "Arcturus",
        "distance": 37,
        "longitude": 15,
        "latitude": 69,
        "size": 30,
        "hieroglyph": "𓇓",
        "egyptian_name": "Was Scepter",
        "gardiner": "S39/S40",
        "description": "Power and Dominion",
        "color": "#FFA500",
    },
    {
        "name": "Achernar",
        "distance": 139,
        "longitude": 300,
        "latitude": -58.8,
        "size": 30,
        "hieroglyph": "𓈗",
        "egyptian_name": "Water/Waves",
        "gardiner": "N35",
        "description": "Waters of Nun",
        "color": "#1E90FF",
    },
    # Count=3 consensus stars
    {
        "name": "Bellatrix",
        "distance": 250,
        "longitude": 210,
        "latitude": -18,
        "size": 25,
        "hieroglyph": "𓇼",
        "egyptian_name": "Star",
        "gardiner": "N14",
        "description": "Celestial Star",
        "color": "#F8F8FF",
    },
    {
        "name": "Mira",
        "distance": 300,
        "longitude": 160,
        "latitude": -58,
        "size": 25,
        "hieroglyph": "𓅛",
        "egyptian_name": "Ba Bird",
        "gardiner": "G29/G53",
        "description": "The Soul",
        "color": "#FFEFD5",
    },
    {
        "name": "Delta Cancri",
        "distance": 180,
        "longitude": 200,
        "latitude": 23,
        "size": 25,
        "hieroglyph": "𓆤",
        "egyptian_name": "Bee",
        "gardiner": "L2",
        "description": "Industrious Order",
        "color": "#FFFFE0",
    },
    {
        "name": "Alnilam",
        "distance": 2000,
        "longitude": 275,
        "latitude": -2,
        "size": 30,
        "hieroglyph": "𓌂",
        "egyptian_name": "Crook",
        "gardiner": "S38/S42",
        "description": "Shepherd’s Staff",
        "color": "#AFEEEE",
    },
    {
        "name": "Albireo",
        "distance": 430,
        "longitude": 62,
        "latitude": 5,
        "size": 25,
        "hieroglyph": "𓆣",
        "egyptian_name": "Double Crown",
        "gardiner": "S4/S5",
        "description": "Union of Two Lands",
        "color": "#DA70D6",
    },
    {
        "name": "Algol",
        "distance": 93,
        "longitude": 150,
        "latitude": -22,
        "size": 25,
        "hieroglyph": "𓆄",
        "egyptian_name": "Feather/Maat",
        "gardiner": "H6",
        "description": "Star of Fate",
        "color": "#DC143C",
    },
    {
        "name": "Mizar",
        "distance": 86,
        "longitude": 160,
        "latitude": 55,
        "size": 25,
        "hieroglyph": "𓌢",
        "egyptian_name": "Flail",
        "gardiner": "S45",
        "description": "Royal Authority",
        "color": "#F5DEB3",
    },
    {
        "name": "Pleiades",
        "distance": 444,
        "longitude": 167,
        "latitude": -23,
        "size": 30,
        "hieroglyph": "𓃞",
        "egyptian_name": "Hathor/Cow",
        "gardiner": "E1/E4/C9",
        "description": "Seven Sisters",
        "color": "#87CEEB",
    },
    {
        "name": "Hadar",
        "distance": 390,
        "longitude": 315,
        "latitude": 1.3,
        "size": 30,
        "hieroglyph": "𓃩",
        "egyptian_name": "Hippopotamus",
        "gardiner": "E24/E25",
        "description": "River Beast",
        "color": "#A9A9A9",
    },
    {
        "name": "Van Maanen's Star",
        "distance": 14,
        "longitude": 70,
        "latitude": -34,
        "size": 20,
        "hieroglyph": "𓂓",
        "egyptian_name": "Ka",
        "gardiner": "D28",
        "description": "Vital Essence",
        "color": "#FFFFFF",
    },
]
